---
version: '3.8'

# Development override configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Override for development - mount source code for hot reloading
  api-gateway:
    environment:
      - GATEWAY_LOG_LEVEL=DEBUG
      - HYBRID_FEATURE_FLAG_SOURCE=local-dev
      - PORTFOLIO_DATABASE_URL=postgresql+psycopg2://dev_user:dev_password@postgres:5432/legacy_coin_trader_dev
    volumes:
      - ./services/api_gateway:/app/services/api_gateway
      - ./crypto_bot:/app/crypto_bot
      - ./libs:/app/libs
      - ./microservice_architecture.yaml:/app/microservice_architecture.yaml
      - /app/services/api_gateway/__pycache__  # Exclude cache
    command: [
      "uvicorn",
      "services.api_gateway.main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "--reload"
    ]

  legacy-monolith:
    environment:
      LEGACY_LOG_LEVEL: DEBUG
      LEGACY_CONFIG_PATH: /opt/legacy/app/config/config.yaml
    volumes:
      - .:/opt/legacy/app

  trading-engine:
    environment:
      TRADING_ENGINE_LOG_LEVEL: DEBUG
      TRADING_ENGINE_CYCLE_INTERVAL: 300  # Slower cycles for development
    volumes:
      - ./services/trading_engine:/app/services/trading_engine
      - ./services/interface_layer:/app/services/interface_layer
      - /app/__pycache__

  market-data:
    environment:
      - MARKET_DATA_LOG_LEVEL=DEBUG
      - MARKET_DATA_CACHE_ENABLED=false  # Disable caching for development
    volumes:
      - ./services/market_data:/app/services/market_data
      - ./crypto_bot:/app/crypto_bot
      - ./libs:/app/libs
      - ./schema:/app/schema
      - /app/services/market_data/__pycache__

  portfolio:
    environment:
      - PORTFOLIO_LOG_LEVEL=DEBUG
      - PORTFOLIO_PAPER_TRADING=true  # Force paper trading in development
      - PORTFOLIO_DATABASE_URL=postgresql+psycopg2://dev_user:dev_password@postgres:5432/legacy_coin_trader_dev
    volumes:
      - ./services/portfolio:/app/services/portfolio
      - ./crypto_bot:/app/crypto_bot
      - ./libs:/app/libs
      - /app/services/portfolio/__pycache__

  strategy-engine:
    environment:
      - STRATEGY_ENGINE_LOG_LEVEL=DEBUG
    volumes:
      - ./services/strategy_engine:/app/services/strategy_engine
      - ./crypto_bot:/app/crypto_bot
      - ./libs:/app/libs
      - ./schema:/app/schema
      - /app/services/strategy_engine/__pycache__

  token-discovery:
    environment:
      - TOKEN_DISCOVERY_LOG_LEVEL=DEBUG
      - TOKEN_DISCOVERY_SCAN_INTERVAL=60  # Faster scanning for development
    volumes:
      - ./services/token_discovery:/app/services/token_discovery
      - ./crypto_bot:/app/crypto_bot
      - ./libs:/app/libs
      - ./schema:/app/schema
      - /app/services/token_discovery/__pycache__

  execution:
    environment:
      - EXECUTION_LOG_LEVEL=DEBUG
      - EXECUTION_DRY_RUN=true  # Force dry run in development
    volumes:
      - ./services/execution:/app/services/execution
      - ./crypto_bot:/app/crypto_bot
      - ./config:/app/config
      - ./libs:/app/libs
      - /app/services/execution/__pycache__

  monitoring:
    environment:
      - MONITORING_LOG_LEVEL=DEBUG
    volumes:
      - ./services/monitoring:/app/services/monitoring
      - ./crypto_bot:/app/crypto_bot
      - ./libs:/app/libs
      - ./logs:/app/logs
      - ./schema:/app/schema
      - /app/services/monitoring/__pycache__

  frontend:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - HYBRID_FEATURE_FLAG_SOURCE=local-dev
    volumes:
      - ./frontend:/app
      - ./static:/app/static
      - ./templates:/app/templates
      - /app/__pycache__

  # Development database for testing
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: legacy_coin_trader_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d legacy_coin_trader_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
