# Test configuration with fewer symbols to verify evaluation pipeline
# Copy of main config with reduced symbol list

# Basic configuration
mode: auto
execution_mode: paper
timeframe: 15m
loop_interval_minutes: 5

# Reduced symbol list for testing
symbols:
  - BTC/USD
  - ETH/USD
  - SOL/USD
  - ADA/USD
  - DOT/USD
  - LINK/USD
  - AVAX/USD
  - MATIC/USD
  - UNI/USD
  - ATOM/USD

# Signal filtering
min_confidence_score: 0.05
signal_threshold: 0.1

# Risk management
max_position_size: 0.1
stop_loss_percent: 0.05
take_profit_percent: 0.15

# Data collection
ohlcv_candles: 200
timeframes: [1m, 5m, 15m, 1h, 4h]

# Paper wallet
paper_wallet_balance: 10000.0
