apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
{{ include "api-gateway.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "api-gateway.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
