---
trading_engine:
  port: 8001
  host: "0.0.0.0"

  # Redis configuration
  redis_host: "localhost"
  redis_port: 6379

  # API Gateway configuration
  api_gateway_host: "localhost"
  api_gateway_port: 8000

  # Service authentication
  service_auth_token: "legacy-coin-trader-service-token-2024"

  # Trading configuration
  cycle_interval: 120  # 2 minutes between cycles
  batch_size: 25
  batch_delay: 1.0

  # Default symbols
  default_symbols:
    - "BTC/USD"
    - "ETH/USD"
    - "SOL/USD"
    - "ADA/USD"
    - "DOT/USD"
    - "LINK/USD"
    - "UNI/USD"
    - "AAVE/USD"
    - "AVAX/USD"
    - "MATIC/USD"

  # Risk management
  max_risk_per_trade: 0.05  # 5% of balance
  max_position_size_pct: 0.2  # 20% of balance

  # Market data
  default_timeframe: "1h"

  # Performance monitoring
  enable_performance_monitoring: true
  performance_metrics_interval: 60

  # Health checks
  health_check_interval: 30
  max_consecutive_failures: 3
