apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-discovery.fullname" . }}
  labels:
{{ include "token-discovery.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "token-discovery.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
