managed_secrets:
  config:
    - path: solana_scanner.api_keys.bitquery
      env: BITQUERY_KEY
      required: false
      description: Bitquery API key injected from the managed secret store.
    - path: solana_scanner.api_keys.moralis
      env: MORALIS_KEY
      required: false
      description: Moralis API key injected from the managed secret store.
  environment:
    - name: API_KEY
      required: true
      description: Primary Kraken API key used for trading operations.
    - name: API_SECRET
      required: true
      description: Primary Kraken API secret used for trading operations.
    - name: KRAKEN_API_KEY
      required: true
      description: Compatibility alias for Kraken API key.
    - name: KRAKEN_API_SECRET
      required: true
      description: Compatibility alias for Kraken API secret.
    - name: SECURITY_JWT_SECRET_KEY
      required: true
      description: JWT signing secret for protected API endpoints.
    - name: SESSION_SECRET_KEY
      required: true
      description: Flask session secret used by the web frontend.
    - name: JWT_SECRET_KEY
      required: false
      description: Legacy JWT secret variable maintained for backwards compatibility.
    - name: TELEGRAM_TOKEN
      required: false
      description: Telegram bot token for notifications.
    - name: TELEGRAM_CHAT_ID
      required: false
      description: Telegram chat identifier for bot alerts.
    - name: HELIUS_KEY
      required: false
      description: Helius API key for Solana integrations.
    - name: BITQUERY_KEY
      required: false
      description: Bitquery API key referenced directly by auxiliary tooling.
    - name: MORALIS_KEY
      required: false
      description: Moralis API key referenced directly by auxiliary tooling.
    - name: PUMPFUN_API_KEY
      required: false
      description: Pump.fun API key for Solana scanners.
    - name: RAYDIUM_API_KEY
      required: false
      description: Raydium API key for liquidity monitoring.
    - name: COINBASE_API_KEY
      required: false
      description: Coinbase API key for optional exchange integrations.
    - name: COINBASE_API_SECRET
      required: false
      description: Coinbase API secret for optional exchange integrations.
    - name: LUNARCRUSH_API_KEY
      required: false
      description: LunarCrush sentiment API key.
