coinbase_api_key: ''
coinbase_api_secret: ''
coinbase_passphrase: ''
exchange: kraken
mode: cex
paper_wallet_balance: 5405.968282633234
telegram_chat_id: '827777274'
telegram_token: 8126215032:AAEhQZLiXpssauKf0ktQsq1XqXl94QriCdE
wallet_address: EoiVpzLA6b6JBKXTB5WRFor3mPkseM6UisLHt8qK9g1c
