adaptive_scan:
  atr_baseline: 0.003
  enabled: true
  max_factor: 15.0
bandit:
  alpha0: 2
  beta0: 1
  enabled: true
  explore_pct: 0.3
bounce_scalper:
  atr_normalization: true
  atr_period: 8
  atr_window: 8
  cooldown_enabled: false
  cooldown_seconds: 60
  down_candles: 1
  ema_window: 30
  lookback: 150
  max_concurrent_signals: 12
  max_drawdown: 0.25
  min_score: 0.09673826786987336
  pattern_timeframe: 1m
  rsi_overbought_pct: 80
  rsi_oversold_pct: 20
  rsi_window: 10
  stop_loss_atr_mult: 0.8217711534978719
  stop_loss_pct: 0.01
  take_profit_atr_mult: 2.397437260113053
  take_profit_pct: 0.02
  trend_ema_fast: 5
  trend_ema_slow: 15
  up_candles: 1
  vol_window: 10
  vol_zscore_threshold: 1.5
  volume_multiple: 2.340306476069623
  zscore_threshold: 0.8
breakout:
  adx_threshold: 12
  atr_buffer_mult: 0.02
  bb_length: 8
  bb_std: 1.8
  dc_length: 12
  kc_length: 8
  kc_mult: 1.2
  momentum_filter: true
  squeeze_threshold: 0.008
  vol_multiplier: 1.5
  volume_window: 10
cycle_bias:
  enabled: true
  mvrv_url: https://api.alternative.me/v2/onchain/mvrv
  nupl_url: https://api.alternative.me/v2/onchain/nupl
  sopr_url: https://api.alternative.me/v2/onchain/sopr
enhanced_backtesting:
  batch_size: 100
  continuous_mode: true
  enabled: true
  lookback_days: 45
  max_drawdown_threshold: 0.5
  max_workers: 8
  min_sharpe_threshold: 0.2
  min_volume_usd: 500000
  min_win_rate: 0.3
  refresh_interval_hours: 6
  results_cache_dir: crypto_bot/logs/backtest_results
  strategies_to_test:
  - trend
  - momentum_bot
  - grid_bot
  - bounce_scalper
  - sniper_bot
  - micro_scalp
  timeframes:
  - 15m
  - 1h
  - 4h
  top_pairs_count: 20
  use_gpu: true
exchange: kraken
exchange_market_types:
- spot
- futures
exec:
  allow_market_orders: true
  order_retry_interval: 0.5
execution_mode: dry_run

# Paper Wallet Configuration for Dry Run Mode
paper_wallet:
  enabled: true
  initial_balance: 10000.0
  max_open_trades: 10
  allow_short: true
  config_file: "crypto_bot/paper_wallet_config.yaml"

exit_strategy:
  adaptive_trailing:
    base_trailing_pct: 0.008
    enabled: true
    momentum_trailing_adjustments:
      moderate_momentum: 0.8
      strong_momentum: 0.6
      very_strong_momentum: 0.4
      weak_momentum: 1.0
  breakout_momentum:
    breakout_threshold: 0.015
    enabled: true
    momentum_extension_multiplier: 2.5
    volume_breakout_multiplier: 3.0
  fib_momentum_scaling: true
  fib_tp_enabled: true
  min_gain_to_trail: 0.005
  momentum_aware_exits: true
  momentum_continuation:
    enabled: true
    macd_momentum_threshold: 0.001
    price_acceleration_threshold: 0.002
    rsi_momentum_threshold: 65
    volume_momentum_threshold: 1.5
  momentum_exit_delays:
    enabled: true
    strong_momentum_delay_seconds: 30
    very_strong_momentum_delay_seconds: 60
  momentum_partial_exits: true
  momentum_tp_multipliers:
    moderate_momentum: 1.5
    strong_momentum: 2.0
    very_strong_momentum: 3.0
    weak_momentum: 1.0
  momentum_tp_scaling: true
  momentum_trail_adjustment: true
  partial_exit_momentum_thresholds:
  - exit_pct: 10
    momentum: 0.3
    profit_pct: 0.02
  - exit_pct: 15
    momentum: 0.5
    profit_pct: 0.03
  - exit_pct: 20
    momentum: 0.7
    profit_pct: 0.05
  - exit_pct: 25
    momentum: 0.85
    profit_pct: 0.08
  partial_levels:
  - 20
  - 40
  - 60
  - 80
  - 100
  scale_out: true
  take_profit_pct: 0.04
  trailing_stop_factor: 1.1
  trailing_stop_pct: 0.008
exits:
  default_sl_pct: 0.008
  default_tp_pct: 0.045
  trailing_stop_pct: 0.008
grid_bot:
  arbitrage_pairs:
  - BTC/USDT
  - SOL/USDC
  - ETH/USDT
  - MATIC/USDC
  arbitrage_threshold: 0.0008
  atr_normalization: true
  atr_period: 8
  breakout_mult: 1.5
  cooldown_bars: 0
  dynamic_grid: true
  leverage: 5
  max_active_legs: 20
  min_range_pct: 0.0002
  range_window: 10
  spacing_factor: 0.15
  trend_ema_fast: 25
  trend_ema_slow: 100
  use_ml_center: true
  vol_zscore_threshold: 1.2
  volume_filter: false
  volume_ma_window: 10
  volume_multiple: 1.2
liquidity_check: true
liquidity_depth: 3
max_age_days: 60
max_change_pct: 30
max_concurrent_ohlcv: 8
max_drawdown: 0.35
max_latency_ms: 300
max_ohlcv_failures: 8
max_open_trades: 30
max_parallel: 100
max_slippage_pct: 0.3
max_spread_pct: 4
max_vol: 100000000
max_ws_limit: 300
metrics_backend: csv
metrics_enabled: true
metrics_output_file: crypto_bot/logs/metrics.csv
micro_scalp:
  atr_period: 8
  confirm_bars: 0
  cooldown_seconds: 30
  ema_fast: 1
  ema_slow: 3
  fresh_cross_only: false
  imbalance_filter: false
  max_concurrent_signals: 25
  max_drawdown: 0.2
  min_atr_pct: 0.0003
  min_score: 0.06
  stop_loss_pct: 0.005
  take_profit_pct: 0.02
  trend_fast: 10
  trend_filter: false
  trend_slow: 25
  trend_timeframe: 1m
  vol_window: 10
  volume_window: 10
  wick_pct: 0.08
min_symbol_age_days: 0
ml_enabled: true
ml_signal_model:
  enabled: true
  weight: 0.8
mode: auto
momentum_exploiter:
  enabled: true
  lookback: 10
  max_positions: 25
  stop_loss_pct: 0.008
  take_profit_pct: 0.035
  threshold: 0.01
ohlcv_quality:
  fallback_to_rest: true
  max_retry_attempts: 2
  min_data_ratio: 0.5
  min_required_candles: 20
  rest_fallback_timeout: 25
  retry_incomplete: true
optimization:
  enabled: true
  interval_days: 0.5
  parameter_ranges:
    bounce_scalper:
      stop_loss:
      - 0.003
      - 0.005
      - 0.008
      take_profit:
      - 0.02
      - 0.035
      - 0.05
    grid_bot:
      stop_loss:
      - 0.003
      - 0.005
      - 0.008
      - 0.01
      take_profit:
      - 0.015
      - 0.025
      - 0.04
      - 0.06
    momentum_bot:
      stop_loss:
      - 0.005
      - 0.008
      - 0.01
      - 0.015
      take_profit:
      - 0.03
      - 0.05
      - 0.08
      - 0.12
    sniper_bot:
      stop_loss:
      - 0.005
      - 0.008
      - 0.012
      - 0.018
      take_profit:
      - 0.025
      - 0.04
      - 0.06
      - 0.09
    trend:
      stop_loss:
      - 0.005
      - 0.008
      - 0.01
      - 0.015
      - 0.02
      take_profit:
      - 0.025
      - 0.04
      - 0.06
      - 0.08
      - 0.12
      - 0.15
portfolio_rotation:
  enabled: true
  interval_days: 0.25
  rebalance_threshold: 0.03
  scoring_method: momentum
  top_assets: 15
preferred_chain: solana
rest_ohlcv_timeout: 30
risk:
  atr_long_window: 50
  atr_period: 14
  atr_short_window: 14
  bull_fng: 101
  bull_sentiment: 101
  max_drawdown: 0.25
  max_funding_rate: 1.0
  max_pair_drawdown: 0.0
  max_volatility_factor: 1.5
  min_atr_pct: 0.0
  min_expected_value: 0.0
  min_fng: 0
  min_sentiment: 0
  min_volume: 0.0
  pair_drawdown_lookback: 20
  risk_pct: 0.01
  stop_loss_atr_mult: 2.0
  stop_loss_pct: 0.01
  take_profit_atr_mult: 4.0
  take_profit_pct: 0.02
  trade_size_pct: 0.1
  volume_threshold_ratio: 0.1
safety:
  max_error_count: 15
  restart_on_error: true
scalp_timeframe: 1m
scan_in_background: true
scan_lookback_limit: 500
scan_markets: true
signal_fusion:
  enabled: true
  fusion_method: weight
  min_confidence: 0.015
  strategies:
  - - trend
    - 0.4
  - - micro_scalp
    - 0.35
  - - sniper_bot
    - 0.25
sl_pct: 0.008
sniper_bot:
  atr_window: 8
  breakout_pct: 0.011236940825431006
  cooldown_seconds: 45
  fallback_atr_mult: 1.0
  fallback_volume_mult: 1.0
  max_concurrent_signals: 15
  max_drawdown: 0.25
  max_history: 15
  max_slippage_bps: 15
  min_liquidity_usd: 100
  price_fallback: true
  stop_loss_pct: 0.0063797342686504575
  take_profit_pct: 0.050447594063026804
  volume_multiple: 2.340419908826357
  volume_window: 2
solana_scalping:
  macd_fast: 8
  macd_signal: 6
  macd_slow: 18
  overbought: 80.0
  oversold: 20.0
  rsi_window: 6
solana_scanner:
  api_keys:
    bitquery: YOUR_KEY
    moralis: YOUR_KEY
  enabled: true
  gecko_search: true
  interval_minutes: 0.15
  max_tokens_per_scan: 150
  min_volume_usd: 100
solana_slippage_bps: 15
solana_symbols: []
stop_loss_pct: 0.008
strategy_allocation:
  bounce_scalper: 0.15
  grid_bot: 0.15
  micro_scalp_bot: 0.3
  sniper_bot: 0.25
  trend_bot: 0.15
strategy_router:
  bandit_enabled: true
  bounce_timeframe: 3m
  breakout_timeframe: 10m
  fast_path:
    breakout_max_bandwidth: 0.025
    breakout_squeeze_window: 8
    breakout_volume_multiplier: 4
    trend_adx_threshold: 15
  mean_reverting_timeframe: 45m
  regimes:
    bounce:
    - bounce_scalper
    breakout:
    - breakout_bot
    mean-reverting:
    - mean_bot
    - dip_hunter
    - stat_arb_bot
    scalp:
    - micro_scalp
    - micro_scalp_bot
    sideways:
    - grid
    - maker_spread
    - range_arb_bot
    trending:
    - trend
    - trend_bot
    - momentum_bot
    - lstm_bot
    volatile:
    - sniper_bot
    - sniper_solana
    - flash_crash_bot
    - meme_wave_bot
    - hft_engine
  scalp_timeframe: 1m
  sideways_timeframe: 45m
  trending_timeframe: 45m
  volatile_timeframe: 1m
symbol_filter:
  change_pct_percentile: 3
  correlation_max_pairs: 250
  http_timeout: 3
  kraken_batch_size: 300
  log_ticker_exceptions: true
  max_correlation: 0.85
  max_spread_pct: 5
  min_volume_usd: 25
  ticker_retry_attempts: 3
  uncached_volume_multiplier: 1.2
  volume_percentile: 10
symbol_refresh_minutes: 0.15
take_profit_pct: 0.045
tax_tracking:
  enabled: true
  export_path: crypto_bot/logs/tax_trades.csv
telegram:
  balance_updates: true
  chat_admins: 827777274
  chat_id: 827777274
  command_cooldown: 2
  connect_timeout: 60.0
  connection_pool_size: 8
  enabled: true
  fail_silently: true
  max_retries: 5
  read_timeout: 60.0
  retry_delay_seconds: 10
  status_updates: true
  timeout_seconds: 60
  token: 8126215032:AAEhQZLiXpssauKf0ktQsq1XqXl94QriCdE
  trade_updates: true
  write_timeout: 60.0
telegram_ctl:
  enabled: true
  update_interval: 15
testing_mode: false
timeframe: 10m
timeframes:
- 1m
- 5m
- 10m
- 15m
- 1h
- 4h
top_n_symbols: 150
tp_mult: 2.5
tp_pct: 0.045
trade_size_pct: 0.25
trend:
  atr_period: 8
  k: 0.9
  trend_ema_fast: 10
  trend_ema_slow: 25
ultra_scalp_bot:
  atr_window: 3
  enabled: true
  max_concurrent: 30
  min_score: 0.034262190740007054
  stop_loss_pct: 0.003361080934308343
  take_profit_pct: 0.026817922291809047
  timeframe: 1m
  volume_mult: 2.129581467112397
use_websocket: true
volatility_harvester:
  atr_threshold: 0.002
  enabled: true
  max_positions: 20
  stop_loss_pct: 0.01
  take_profit_pct: 0.04
  volume_spike: 2.0
ws_failures_before_disable: 5
ws_max_retries: 5
ws_ohlcv_timeout: 30
ws_ping_interval: 10
ws_reconnect_delay: 15
