allow_short: true
bounce_scalper:
  enabled: true
  max_concurrent_signals: 5
  min_score: 0.01
breakout:
  enabled: true
  min_score: 0.01
circuit_breaker:
  enabled: true
  expected_exception: Exception
  failure_threshold: 10
  half_open_max_calls: 3
  recovery_timeout: 300
comprehensive_mode_optimization:
  adaptive_rate_limiting: true
  batch_chunk_size: 25
  enable_memory_optimization: true
  enable_progress_tracking: true
  memory_cleanup_interval: 50
cycle_delay_seconds: 120
data_validation:
  allow_empty_volume: true
  max_data_age_minutes: 60
  min_data_points: 50
  require_volume: false
  validate_ohlcv: true
enhanced_backtesting:
  enabled: false
enhanced_scanning:
  data_sources:
    orderbook:
    - jupiter
    price:
    - pyth
    - jupiter
    volume:
    - birdeye
  discovery_sources:
  - basic_scanner
  - dex_aggregators
  enable_pyth_prices: true
  enable_sentiment: false
  enabled: true
  max_spread_pct: 1.5
  max_tokens_per_scan: 20
  min_confidence: 0.5
  min_liquidity_score: 0.6
  min_score_threshold: 0.4
  min_strategy_fit: 0.6
  min_volume_usd: 5000
  scan_interval: 30
error_handling:
  continue_on_error: true
  exponential_backoff: true
  fallback_data_sources: true
  graceful_degradation: true
  log_errors: true
  max_backoff: 30.0
  max_retries: 2
  retry_delay: 2.0
  scan_error_cooldown: 300
  scan_error_threshold: 5
exchange: kraken
execution_mode: paper
exit_strategy:
  min_gain_to_trail: 0.005
  momentum_aware_exits: true
  momentum_tp_scaling: true
  momentum_trail_adjustment: true
  real_time_monitoring:
    check_interval_seconds: 5
    enabled: true
  take_profit_pct: 0.04
  trailing_stop_pct: 0.01
exits:
  default_sl_pct: 0.008
  default_tp_pct: 0.045
  trailing_stop_pct: 0.008
kraken:
  enabled: true
  max_retries: 3
  rate_limit: true
  retry_on_failure: true
  sandbox: false
  timeout: 30
max_concurrent_ohlcv: 10
min_confidence_score: 0.001
mode: auto
pipeline_stability:
  circuit_breaker_enabled: true
  circuit_breaker_threshold: 3
  continue_on_error: true
  disable_complex_filters: false
  enable_rate_limiting: true
  fallback_to_simple_mode: true
  max_concurrent_requests: 10
  max_failures_per_cycle: 5
  rate_limit_delay: 1.0
  request_timeout: 20
  retry_attempts: 2
position_sync_enabled: true
process_all_symbols: true
rate_limiting:
  burst_limit: 3
  burst_window: 5.0
  enabled: true
  max_retries: 3
  requests_per_minute: 30
  retry_delay: 2.0
regime_timeframes:
- 4h
- 1d
- 1w
risk:
  enable_partial_exits: true
  enable_trailing_stop: true
  max_drawdown: 0.25
  max_positions: 10
  max_risk_per_trade: 0.05
  max_total_risk: 0.2
  min_position_size_usd: 10
  partial_exit_pct: 0.5
  position_size_pct: 0.2
  stop_loss_pct: 0.02
  take_profit_pct: 0.04
  trailing_stop_pct: 0.01
scan_cache:
  auto_cleanup: true
  max_age_hours: 12
  max_cache_size: 500
  min_score_threshold: 0.4
  persist_to_disk: true
  review_interval_minutes: 20
scan_monitoring:
  alert_on_scan_failures: true
  enable_scan_metrics: true
  log_scan_results: true
  max_scan_logs: 1000
  scan_metrics_interval: 60
  track_scan_performance: true
skip_symbol_filters: true
solana_scanner:
  api_keys:
    bitquery: YOUR_KEY
    moralis: YOUR_KEY
  enabled: true
  gecko_search: true
  interval_minutes: 30
  max_tokens_per_scan: 100
  min_volume_usd: 5000
strategy_evaluation_mode: mapped
strategy_router:
  regimes:
    breakout:
    - breakout_bot
    - sniper_bot
    - ultra_scalp_bot
    mean-reverting:
    - mean_bot
    - range_arb_bot
    - stat_arb_bot
    sideways:
    - market_making_bot
    - grid_bot
    - maker_spread
    trending:
    - momentum_bot
    - lstm_bot
    - trend_bot
    volatile:
    - arbitrage_engine
    - volatility_harvester
    - flash_crash_bot
symbol_batch_size: 100
symbol_validation:
  allowed_quotes:
  - USD
  - EUR
  - USDC
  - USDT
  enabled: true
  max_price_deviation: 0.1
  max_symbol_length: 25
  min_liquidity_score: 0.6
  min_volume_usd: 5000
  require_kraken_support: true
  skip_unknown_addresses: true
  strict_mode: false
  timeout_seconds: 10
  validate_liquidity: true
  validate_price: true
  validate_volume: true
symbols:
- BTC/USD
- ETH/USD
- SOL/USD
- ADA/USD
- DOT/USD
- LINK/USD
- UNI/USD
- AAVE/USD
- AVAX/USD
- MATIC/USD
- ATOM/USD
- NEAR/USD
telegram:
  balance_updates: false
  enabled: true
  status_updates: false
  trade_updates: true
testing_mode: true
timeframe: 1h
use_enhanced_ohlcv_fetcher: true
use_trade_manager_as_source: true
use_websocket: true
websocket:
  connection_timeout: 30
  enabled: true
  health_check:
    enabled: true
    failure_threshold: 3
    interval: 30
  kraken:
    enhanced_error_handling: true
    health_monitoring: true
    message_validation: true
  max_connections: 10
  max_message_size: 1048576
  monitoring:
    alert_on_failures: true
    log_level: INFO
    metrics_interval: 60
  ping_interval: 20
  ping_timeout: 10
  reconnect:
    backoff_factor: 2.0
    base_delay: 1.0
    max_attempts: 10
    max_delay: 60.0
  solana:
    enhanced_monitor: true
    exponential_backoff: true
    health_checks: true
    message_validation: true
