allow_short: true
bounce_scalper:
  enabled: true
  max_concurrent_signals: 20  # Increased for scalping
  min_score: 0.01

# OPTIMIZED Scalp strategy configurations - Higher RR ratios for better profitability
ultra_scalp_bot:
  enabled: true
  max_concurrent_signals: 25  # Reduced to focus on quality signals
  min_score: 0.08  # Higher quality threshold
  timeframe: 1m
  stop_loss_pct: 0.005  # Slightly wider stops
  take_profit_pct: 0.020  # 4:1 RR ratio for better profitability
  trailing_stop_enabled: true
  trailing_stop_pct: 0.008

micro_scalp_bot:
  enabled: true
  max_concurrent_signals: 20
  min_score: 0.06
  timeframe: 1m
  ema_fast: 3  # Slightly slower for better signal quality
  ema_slow: 8
  stop_loss_pct: 0.006
  take_profit_pct: 0.024  # 4:1 RR ratio
  confirmation_timeframes: [5m, 15m]  # Multi-timeframe confirmation

momentum_exploiter:
  enabled: true
  max_concurrent_signals: 15
  min_score: 0.07
  timeframe: 1m
  stop_loss_pct: 0.008
  take_profit_pct: 0.032  # 4:1 RR ratio - let winners run
  momentum_threshold: 0.015  # Strong momentum required
  volume_multiplier: 1.5

# DISABLED - Focus on top 3 strategies
dex_scalper:
  enabled: false  # Disabled to reduce strategy overlap
  max_concurrent_signals: 25
  min_score: 0.03
  timeframe: 1m
  ema_fast: 3
  ema_slow: 8
  stop_loss_pct: 0.004
  take_profit_pct: 0.010
  gas_threshold_gwei: 15.0

hft_engine:
  enabled: false  # Disabled - too tight targets, focus on quality over quantity
  max_concurrent_signals: 50
  min_score: 0.02
  timeframe: 1m
  stop_loss_pct: 0.002
  take_profit_pct: 0.006
  queue_timeout_ms: 2000

volatility_harvester:
  enabled: false  # Disabled to focus on core strategies
  max_concurrent_signals: 15
  min_score: 0.05
  timeframe: 1m
  stop_loss_pct: 0.006
  take_profit_pct: 0.014
  atr_threshold: 0.001

maker_spread:
  enabled: false  # Disabled - not optimal for fast profitability
  max_concurrent_signals: 10
  min_score: 0.08
  timeframe: 1m
  stop_loss_pct: 0.008
  take_profit_pct: 0.016
  max_spread_bp: 8.0
breakout:
  enabled: true
  min_score: 0.01
circuit_breaker:
  enabled: true
  expected_exception: Exception
  failure_threshold: 10
  half_open_max_calls: 3
  recovery_timeout: 300
comprehensive_mode_optimization:
  adaptive_rate_limiting: true
  batch_chunk_size: 30          # Optimized for quality over quantity
  enable_memory_optimization: true
  enable_progress_tracking: true
  memory_cleanup_interval: 20   # More frequent cleanup
cycle_delay_seconds: 18          # Faster cycles for rapid profitability
indicator_lookback: 15           # Slightly increased for better signal quality
# NEW - Profitability optimizations
profit_focus_mode: true          # Prioritize high-probability trades
min_profit_potential: 0.015      # Only trade setups with >1.5% profit potential
max_trade_frequency: 8           # Limit to 8 trades per hour for quality control
data_validation:
  allow_empty_volume: true
  max_data_age_minutes: 60
  min_data_points: 50
  require_volume: false
  validate_ohlcv: true
enhanced_backtesting:
  enabled: false
enhanced_scanning:
  data_sources:
    orderbook:
    - jupiter
    price:
    - pyth
    - jupiter
    volume:
    - birdeye
  discovery_sources:
  - basic_scanner
  - dex_aggregators
  enable_pyth_prices: true
  enable_sentiment: false
  enabled: true
  max_spread_pct: 1.2            # Tighter spreads for better execution
  max_tokens_per_scan: 20        # Focus on quality over quantity
  min_confidence: 0.45           # Higher confidence threshold
  min_liquidity_score: 0.60      # Stricter liquidity requirements
  min_score_threshold: 0.35      # Higher quality threshold
  min_strategy_fit: 0.65         # Better strategy alignment
  min_volume_usd: 5000           # Higher volume requirement for better markets
  scan_interval: 15              # Faster scanning for quick opportunities
  # NEW - Profitability filters
  min_price_movement: 0.008      # Require minimum recent volatility
  max_price_staleness: 30        # Price data must be fresh
  volatility_filter: true        # Only trade volatile pairs for scalping
  min_daily_volume_multiplier: 2.0  # Volume must be 2x average
error_handling:
  continue_on_error: true
  exponential_backoff: true
  fallback_data_sources: true
  graceful_degradation: true
  log_errors: true
  max_backoff: 30.0
  max_retries: 2
  retry_delay: 2.0
  scan_error_cooldown: 300
  scan_error_threshold: 5
exchange: kraken
execution_mode: paper
exit_strategy:
  min_gain_to_trail: 0.012      # Higher threshold before trailing - let winners run
  momentum_aware_exits: true
  momentum_tp_scaling: true
  momentum_trail_adjustment: true
  # NEW - Advanced exit optimizations
  scale_out_enabled: true        # Enable partial exits at different levels
  scale_out_levels:              # Multiple profit-taking levels
    - pct: 0.015                 # Take 25% at 1.5% profit
      portion: 0.25
    - pct: 0.030                 # Take 25% at 3.0% profit
      portion: 0.25
    - pct: 0.060                 # Take 50% at 6.0% profit
      portion: 0.50
  time_based_exits: true         # Exit if position held too long without progress
  max_hold_time_minutes: 45      # Maximum hold time for scalp trades
  breakeven_activation: 0.010    # Move to breakeven after 1% profit
  real_time_monitoring:
    check_interval_seconds: 3    # More frequent monitoring
    enabled: true
  take_profit_pct: 0.08          # Much wider profit targets
  trailing_stop_pct: 0.020       # Generous trailing stops to let winners run
exits:
  default_sl_pct: 0.010          # Slightly wider default stops
  default_tp_pct: 0.080          # 8:1 RR ratio for major targets
  trailing_stop_pct: 0.015       # Better trailing stop activation
  # NEW - Profit protection features
  profit_lock_enabled: true      # Lock in profits at certain levels
  profit_lock_levels:
    - threshold: 0.020           # After 2% profit
      trail_pct: 0.008           # Trail at 0.8%
    - threshold: 0.050           # After 5% profit
      trail_pct: 0.012           # Trail at 1.2%
kraken:
  enabled: true
  max_retries: 3
  rate_limit: true
  retry_on_failure: true
  sandbox: false
  timeout: 30
max_concurrent_ohlcv: 20        # Increased for better parallel processing
min_confidence_score: 0.001
mode: auto
pipeline_stability:
  circuit_breaker_enabled: true
  circuit_breaker_threshold: 3
  continue_on_error: true
  disable_complex_filters: false
  enable_rate_limiting: true
  fallback_to_simple_mode: true
  max_concurrent_requests: 15     # Increased for better throughput
  max_failures_per_cycle: 5
  rate_limit_delay: 0.8           # Slightly faster rate limiting
  request_timeout: 25             # Increased timeout for stability
  retry_attempts: 3               # One more retry for resilience
position_sync_enabled: true
process_all_symbols: true
rate_limiting:
  burst_limit: 8              # Increased burst capacity
  burst_window: 5.0
  enabled: true
  max_retries: 3
  requests_per_minute: 55     # Increased throughput (within Kraken limits)
  retry_delay: 1.2            # Faster retry
regime_timeframes:
- 1m
- 15m
- 1h
- 4h
- 1d
- 1w
risk:
  enable_partial_exits: true
  enable_trailing_stop: true
  max_drawdown: 0.12             # Slightly tighter for protection
  max_positions: 35              # Optimized for focused strategies
  max_risk_per_trade: 0.015      # Increased 3x for meaningful returns (1.5% per trade)
  max_total_risk: 0.25           # Increased total risk capacity
  min_position_size_usd: 25      # Higher minimum for better execution
  partial_exit_pct: 0.33         # Scale out gradually (1/3 at a time)
  position_size_pct: 0.08        # Increased position sizing
  stop_loss_pct: 0.008           # Balanced stops
  take_profit_pct: 0.025         # Wider profit targets
  trailing_stop_pct: 0.010       # More generous trailing stops
  # OPTIMIZED Scalp-specific overrides for profitability
  scalp_stop_loss_pct: 0.006     # Balanced stops for scalp regime
  scalp_take_profit_pct: 0.024   # 4:1 RR ratio for scalp regime
  scalp_max_positions: 45        # Focused concurrent positions
  # NEW - Dynamic risk scaling based on win rate
  dynamic_risk_scaling: true
  win_rate_threshold: 0.55       # Scale up risk if win rate > 55%
  risk_scaling_factor: 1.2       # Increase risk by 20% on good performance
scan_cache:
  auto_cleanup: true
  max_age_hours: 8              # Shorter cache age for fresher data
  max_cache_size: 750           # Increased cache size for better hit rates
  min_score_threshold: 0.3      # Lower threshold for more caching
  persist_to_disk: true
  review_interval_minutes: 15   # More frequent cache reviews
scan_monitoring:
  alert_on_scan_failures: true
  enable_scan_metrics: true
  log_scan_results: true
  max_scan_logs: 1000
  scan_metrics_interval: 60
  track_scan_performance: true
skip_symbol_filters: true
solana_scanner:
  api_keys:
    bitquery: YOUR_KEY
    moralis: YOUR_KEY
  enabled: true
  gecko_search: true
  interval_minutes: 45           # More conservative scanning to reduce 429s
  max_tokens_per_scan: 75        # Lower discovery to reduce GeckoTerminal load
  min_volume_usd: 3000           # Lower threshold for more opportunities
strategy_evaluation_mode: best
strategy_router:
  regimes:
    breakout:
    - breakout_bot
    - sniper_bot
    - ultra_scalp_bot
    mean-reverting:
    - mean_bot
    - range_arb_bot
    - stat_arb_bot
    sideways:
    - market_making_bot
    - grid_bot
    - maker_spread
    trending:
    - momentum_bot
    - lstm_bot
    - trend_bot
    volatile:
    - arbitrage_engine
    - volatility_harvester
    - flash_crash_bot
    scalp:
    - ultra_scalp_bot
    - micro_scalp_bot
    - bounce_scalper
    - momentum_exploiter
    - dex_scalper
    - hft_engine
    - volatility_harvester
    - maker_spread
    scalp_timeframe: 1m
symbol_batch_size: 75          # Optimized for memory vs throughput balance
symbol_validation:
  allowed_quotes:
  - USD
  - EUR
  - USDC
  - USDT
  enabled: true
  max_price_deviation: 0.1
  max_symbol_length: 25
  min_liquidity_score: 0.5
  min_volume_usd: 3000
  require_kraken_support: true
  skip_unknown_addresses: true
  strict_mode: false
  timeout_seconds: 10
  validate_liquidity: true
  validate_price: true
  validate_volume: true
symbols:
- BTC/USD
- ETH/USD
- SOL/USD
- ADA/USD
- DOT/USD
- LINK/USD
- UNI/USD
- AAVE/USD
- AVAX/USD
- MATIC/USD
- ATOM/USD
- NEAR/USD
telegram:
  balance_updates: false
  enabled: true
  status_updates: false
  trade_updates: true
testing_mode: true
timeframe: 15m
use_enhanced_ohlcv_fetcher: true
use_trade_manager_as_source: true
use_websocket: true
websocket:
  connection_timeout: 35          # Slightly longer timeout for stability
  enabled: true
  health_check:
    enabled: true
    failure_threshold: 2          # More sensitive failure detection
    interval: 25                  # More frequent health checks
  kraken:
    enhanced_error_handling: true
    health_monitoring: true
    message_validation: true
  max_connections: 12             # More connections for better throughput
  max_message_size: 1048576
  monitoring:
    alert_on_failures: true
    log_level: INFO
    metrics_interval: 45          # More frequent metrics
  ping_interval: 15               # More frequent pings for better connectivity
  ping_timeout: 8                 # Shorter timeout for faster detection
  reconnect:
    backoff_factor: 1.8           # Slightly less aggressive backoff
    base_delay: 0.8               # Faster initial reconnection
    max_attempts: 12              # More reconnection attempts
    max_delay: 45.0               # Shorter max delay
  solana:
    enhanced_monitor: true
    exponential_backoff: true
    health_checks: true
    message_validation: true

# Advanced Performance Optimization (NEW)
performance_optimization:
  # Memory management
  memory:
    enable_adaptive_gc: true        # Enable adaptive garbage collection
    gc_threshold: 0.75              # Trigger GC at 75% memory usage
    max_memory_usage_pct: 85.0      # Maximum memory usage before aggressive cleanup
    cache_size_limit_mb: 512        # Cache size limit in MB

  # Adaptive concurrency control
  concurrency:
    enable_adaptive_limits: true    # Dynamically adjust concurrency based on performance
    min_concurrent_requests: 2      # Minimum concurrent requests
    max_concurrent_requests: 15     # Reduced for quality focus
    response_time_threshold: 1.2    # Faster target response time
    success_rate_threshold: 0.88    # Higher success rate requirement

  # Advanced caching
  caching:
    enable_intelligent_cache: true  # Enable hit-rate based cache sizing
    cache_hit_rate_threshold: 0.80  # Higher cache hit rate for profitability
    adaptive_ttl: true              # Dynamically adjust cache TTL
    min_cache_ttl: 45               # Longer minimum cache TTL
    max_cache_ttl: 2400             # Longer maximum cache TTL

  # Database optimizations
  database:
    enable_connection_pooling: true # Enable database connection pooling
    pool_size: 10                   # Connection pool size
    max_overflow: 20                # Maximum pool overflow
    pool_timeout: 30                # Pool connection timeout

  # Monitoring and alerting
  monitoring:
    enable_performance_alerts: true # Enable performance-based alerts
    cpu_threshold: 80.0             # CPU usage alert threshold
    memory_threshold: 85.0          # Memory usage alert threshold
    response_time_threshold: 1.8    # Faster response time threshold
    error_rate_threshold: 0.03      # Lower error rate threshold (3%)

# PROFITABILITY OPTIMIZATION SETTINGS (NEW)
profitability_optimization:
  # Target performance metrics
  target_daily_return: 0.025        # Target 2.5% daily return
  target_win_rate: 0.60             # Target 60% win rate
  target_avg_win_loss_ratio: 2.5    # Target 2.5:1 win/loss ratio
  target_max_drawdown: 0.08         # Maximum acceptable drawdown

  # Strategy optimization
  enable_strategy_adaptation: true  # Dynamically adjust strategies based on performance
  performance_review_interval: 300  # Review performance every 5 minutes
  strategy_switch_threshold: 0.15   # Switch strategies if performance drops 15%

  # Risk-adjusted performance
  sharpe_ratio_target: 2.0          # Target Sharpe ratio for risk-adjusted returns
  sortino_ratio_target: 2.5         # Target Sortino ratio (downside risk)

  # Profit acceleration features
  enable_profit_compounding: true   # Reinvest profits for compounding returns
  compounding_frequency: 3600      # Compound every hour
  profit_reinvestment_pct: 0.50    # Reinvest 50% of profits

  # Fast profitability features
  enable_high_frequency_mode: false # Disabled for now - focus on quality
  enable_scalp_acceleration: true  # Accelerate scalp trades when profitable
  acceleration_trigger_win_rate: 0.65  # Accelerate when win rate > 65%
  acceleration_factor: 1.5         # Increase trade frequency by 50%
