replicaCount: 2

image:
  repository: ghcr.io/example/legacycointrader-trading-engine
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
commonLabels: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

env: []
envFrom: []

service:
  type: ClusterIP
  port: 80
  targetPort: 8001

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: trading-engine.legacycoin.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}

extraInitContainers: []
extraContainers: []
extraVolumeMounts: []
extraVolumes: []
