replicaCount: 2

image:
  repository: ghcr.io/example/legacycointrader-portfolio
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
commonLabels: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

env: []
envFrom: []

featureFlags:
  HYBRID_MODE_ENABLED: false
  LEGACY_READ_ENABLED: true
  DUAL_WRITE_STRATEGY: mirror
  HYBRID_READ_STRATEGY: compare
  CUTOVER_COMPLETED: false
  CUTOVER_GUARDRAIL_ENABLED: true
  MIGRATION_DRIFT_TOLERANCE: "0.0"

cutoverControls:
  CUTOVER_TARGET_TIMESTAMP: ""
  LEGACY_SERVICE_BASE_URL: ""
  MODERN_SERVICE_BASE_URL: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8003

resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 600m
    memory: 768Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 25
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 12
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75
  behavior: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: portfolio.legacycoin.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}

extraInitContainers: []
extraContainers: []
extraVolumeMounts: []
extraVolumes: []
