apiVersion: v1
kind: Service
metadata:
  name: {{ include "execution.fullname" . }}
  labels:
{{ include "execution.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "execution.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
