---
api_gateway:
  port: 8000
  host: "0.0.0.0"

  # Redis configuration
  redis_host: "localhost"
  redis_port: 6379

  # Service authentication
  service_auth_token: "legacy-coin-trader-service-token-2024"

  # Rate limiting
  rate_limit_requests: 1000
  rate_limit_window: 60

  # Timeouts
  request_timeout: 30
  connect_timeout: 10

  # Service discovery
  service_discovery_enabled: true
  service_ttl: 30

  # Logging
  log_level: "INFO"

  # CORS
  cors_origins:
    - "*"

  # Authentication
  jwt_secret: "legacy-coin-trader-jwt-secret-2024"
  jwt_algorithm: "HS256"
